services:
  app:
    image: swift:6.0
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - external-network
      - internal-network
    depends_on:
      - db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always

volumes:
  postgres_data:

networks:
  external-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
